wFS_avazu_x1_001_2e046612:
    batch_size: 4096
    dataset_id: avazu_x1_0bbde04e
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 10
    embedding_regularizer: 0.05
    epochs: 100
    eval_steps: null
    feature_specs: null
    fs1_context: []
    fs2_context: []
    fs_hidden_units: [800]
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    mlp1_batch_norm: true
    mlp1_dropout: 0.4
    mlp1_hidden_activations: relu
    mlp1_hidden_units: [400, 400, 400]
    mlp2_batch_norm: true
    mlp2_dropout: 0.2
    mlp2_hidden_activations: relu
    mlp2_hidden_units: [800]
    model: FinalMLP
    model_id: FinalMLP_default
    model_root: ./checkpoints/FinalMLP_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_fs: false #关闭特征选择
    verbose: 0
