FinalMLP_Concat_movielenslatest_x1_001_25b6333c:
    batch_size: 4096
    dataset_id: movielenslatest_x1_233328b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_specs: null
    fs1_context: [user_id]
    fs2_context: [item_id]
    fs_hidden_units: [800]
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    mlp1_batch_norm: true
    mlp1_dropout: 0.4
    mlp1_hidden_activations: relu
    mlp1_hidden_units: [400]
    mlp2_batch_norm: true
    mlp2_dropout: 0.2
    mlp2_hidden_activations: relu
    mlp2_hidden_units: [800]
    model: FinalMLP_Concat
    model_id: FinalMLP_Concat_default
    model_root: ./checkpoints/FinalMLP_Concat_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_heads: 10
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_fs: true
    verbose: 1